[project]
name = "hexlet-flask-example"
version = "0.1.0"
description = "My first flask app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
]

[tool.uv.workspace]
members = ["venv"]
